<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>tractor_sensor_kit_launch</name>
  <version>0.0.0</version>
  <description>The tractor_sensor_kit_launch package</description>
  <maintainer email="user@todo.todo">user</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake_auto</buildtool_depend>

  <depend>autoware_launch</depend>
  <depend>tier4_sensor_launch</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
